### ISSUE TITLE
Graviton Support

### ISSUE THREAD

**Issue by lvthillo** [TomRyan-321/crowdstrike-ecs-fargate-pipepline-demo#2]
Thanks for this project. Now, it's more of a question than an issue with your project, but is the same solution also possible for ECS Fargate on Graviton (regarding CrowdStrike compatibility)?

**Comment by TomRyan-321** [comment]
Hi @lvthillo, falcon container does not currently support arm64/graviton workloads, there are plans to add support in future. If you have falcon console access or ask your security team to check the Ideas portal and give it a thumbs up so help highlight more customer demand.
